// Auto-generated by gulp-svg-sprite
 
%sprite:before {
    content: ' ';
    background-image: url("{{{cssPathSvg}}}");
    background-repeat: no-repeat;
    background-size: {{width}}{{units}} {{height}}{{units}};
    display: inline-block;
    {{#cssPathNoSvg}}
    .no-svg & {
        background-image: url("{{{cssPathNoSvg}}}");
    }
    {{/cssPathNoSvg}}
}

{{#sprites}}
.sprite__{{fileName}}:before {
    @extend %sprite;
    background-position: {{x}}{{units}} {{y}}{{units}};
    width: {{width}}{{units}};
    height: {{height}}{{units}};
}
{{/sprites}}